version: '2'
services:
  web:
    build: ./web
    ports: 
      - "80:80"
    volumes:
      - app-volume:/var/www/html:ro

  selfoss:
    build: ./app
    volumes:
      - app-volume:/var/www/html
      - data-volume:/var/www/data

volumes:
  data-volume:
  app-volume:
